[Variables]
bgH=320
dotY=30
highlightColor=254,210,70,230

[Title]
Meter=String
MeterStyle=allText
FontSize=18
FontColor=#highlightColor#
Text=Circuitous
X=130
Y=10

[Version]
Meter=String
MeterStyle=allText
FontColor=#textColor#
FontSize=11
Text=#displayVersion#
X=-2R
Y=1r

[Author]
Meter=String
MeterStyle=allText
FontColor=#textColor#
FontSize=10
Text="Flying Hyrax | flyinghyrax.deviantart.com"
X=133
Y=35

[LicenseHeader]
Meter=String
MeterStyle=headerText
Text=License
X=130
Y=35R
LeftMouseUpAction=["http://creativecommons.org/licenses/by-nc-sa/3.0/"]

[LicenseText]
Meter=String
MeterStyle=subText
FontSize=10
Text="Creative Commons#CRLF#Attribution-NonCommercial-ShareAlike#CRLF#3.0 Unported License"
X=r
Y=r

[CreditsHeader]
Meter=String
MeterStyle=headerText
X=r
Y=35R
Text=Credits + Inspirations

[cred1]
Meter=String
MeterStyle=subText
FontSize=10
Text=Bernd Montag - Sansational
Y=r
LeftMouseUpAction=["http://www.dafont.com/sansation.font"]

[cred2]
Meter=String
MeterStyle=subText
FontSize=10
Y=R
Text=smurfier - lua wizard
LeftMouseUpAction=["http://smurfier.deviantart.com/"]

[cred3]
Meter=String
MeterStyle=subText
FontSize=10
Y=R
Text=kaelri - @include-fu
LeftMouseUpAction=["http://kaelri.deviantart.com/"]

[cred4]
Meter=String
MeterStyle=subText
FontSize=10
Y=R
Text=jsmorley - RegExp guru
LeftMouseUpAction=["http://jsmorley.deviantart.com/"]

[cred5]
Meter=String
MeterStyle=subText
FontSize=10
Y=R
Text=gronostajo - SimplyRound skins
LeftMouseUpAction=["http://gronostajo.deviantart.com/art/SimplyRound-352274699"]

[cred6]
Meter=String
MeterStyle=subText
FontSize=10
Y=R
Text=amc242 - level 11 beta tester
LeftMouseUpAction=["http://amc242.deviantart.com/"]

[cred7]
Meter=String
MeterStyle=subText
FontSize=10
Y=R
Text=lalibi - Etheldrede Pantone skins
LeftMouseUpAction=["http://lalibi.deviantart.com/art/Etheldrede-pantone-361311100"]

[cred8]
Meter=String
MeterStyle=subText
FontSize=10
Y=R
Text="Yahoo! Weather - weather data"
LeftMouseUpAction=["http://weather.yahoo.com"]

[cred9]
Meter=String
MeterStyle=subText
FontSize=10
Y=R
Text="Rainmeter Developer Team"
LeftMouseUpAction=["https://github.com/rainmeter?tab=members"]