[Variables]
bgH=520
bgW=520
dotY=30
highlightColor=254,210,70,230

[Title]
Meter=String
MeterStyle=allText
FontSize=18
FontColor=#highlightColor#
Text=System Monitor
X=130
Y=10

[Author]
Meter=String
MeterStyle=allText
FontColor=#textColor#
FontSize=10
Text="Norbert Ruff | based on Flying Hyrax Circuitous"
X=133
Y=35


[CreditsHeader]
Meter=String
MeterStyle=headerText
X=r
Y=35R
Text=Credits + Inspirations

[cred1]
Meter=String
MeterStyle=subText
FontSize=10
Text=Flying Hyrax Circuitous
Y=r
LeftMouseUpAction=["https://www.deviantart.com/flyinghyrax"]

[cred9]
Meter=String
MeterStyle=subText
FontSize=10
Y=R
Text="Rainmeter Developer Team"
LeftMouseUpAction=["https://github.com/rainmeter?tab=members"]

[LicenseHeader]
Meter=String
MeterStyle=headerText
Text=License
X=130
Y=35R
LeftMouseUpAction=["http://creativecommons.org/licenses/by-nc-sa/3.0/"]

[LicenseText]
Meter=String
MeterStyle=subText
FontSize=10
Text="Creative Commons#CRLF#Attribution-NonCommercial-ShareAlike#CRLF#3.0 Unported License"
X=r
Y=r
