[Rainmeter]
Update=1000
Group=rsm

[Metadata]
Name=RSM | Fan 2
Author=Norbert Ruff | Flying Hyrax | flyinghyrax.deviantart.com
Information=Displays fan RPM using HWiNFO64. HWiNFO64 must be running with Shared Memory support enabled. | You will need to edit the fan2rpm variable in "@Resources\Settings.txt" to tell the skin which sensor to display.
Version=1.0
License=Creative Commons BY-NC-SA 3.0

@include1=#@#Settings.txt
@include2=#@#Apparence\fan.txt

@include3="#@#Styles\common.inc"
@include4="#@#Styles\#orient#.inc"

[Variables]
; Fan-specific configuration
fanRpmRegValue=#fan2rpm#
fanLabel=#fan2Label#
fanMaxRpm=#fanMaxRpm#

@include6="#@#Templates\fanTemplate.inc"
