[Rainmeter]
Update=1000
Group=rsm

[Metadata]
Name=RSM | RAM Temperature
Author=Norbert Ruff | Flying Hyrax | flyinghyrax.deviantart.com
Information=Displays RAM temperature using HWiNFO64. HWiNFO64 must be running with Shared Memory support enabled. | You will need to edit the ramTemp variable in "@Resources\Settings.txt" to tell the skin which sensor to display.
Version=1.0
License=Creative Commons BY-NC-SA 3.0

@include1=#@#Settings.txt
@include2=#@#Apparence\fan.txt

@include3="#@#Styles\common.inc"
@include4="#@#Styles\#orient#.inc"

[Variables]
; Temperature-specific configuration
tempRegValue=#dimm1Temp#
tempLabel=#dimm1Label#
tempPercentFormula=(mTemp/100)

@include6="#@#Templates\tempTemplate.inc"
